### ISSUE TITLE
Perform PAM item expansion on arguments

### ISSUE THREAD

**Issue by Majiir** [z4yx/pam_rssh#13]
## Description

PAM item expansion is a feature of some modules ([source](https://www.gnu.org.ua/software/pam-modules/manual/html_chapter/Intro.html)):

> Some modules perform PAM _item expansion_ on their arguments. It is a feature similar to shell’s variable expansion. During item expansion, any occurrence of `$name` in a string is replaced by the value of the PAM item _name_. If the item in question is not defined, an empty string is substituted instead.

Item information can be queried with [`pam_get_item`](https://man7.org/linux/man-pages/man3/pam_get_item.3.html) ([`get_item`](https://docs.rs/pam-bindings/latest/pam/module/struct.PamHandle.html#method.get_item) in `pam-bindings`).

## Use case

In `pam_rssh`, item expansion would be helpful in `auth_key_file`.

For instance, my system has authorized keys at `/etc/ssh/authorized_keys.d/<user>`. I cannot express this path using `auth_key_file`.

As a bonus, item expansion would allow to replace [this special path logic](https://github.com/z4yx/pam_rssh/blob/d57e15e/src/auth_keys.rs#L88) with an actual parameter default value [as is documented](https://github.com/z4yx/pam_rssh/blob/6f0aa1c/README.md?plain=1#L68).

## Alternatives

I tried this workaround with `authorized_keys_command`:

```bash
#!/usr/bin/env bash
cat "/etc/ssh/authorized_keys.d/$(whoami)"
```

It _sort of_ works, but not in all situations. For example, a simple `su` runs the command as `root`, not as the requesting user. PAM provides both `PAM_USER` and `PAM_RUSER` items to differentiate the requesting user from target user.

**Comment by z4yx** [comment]
That sounds reasonable. Give me some time for developement.

**Comment by z4yx** [comment]
Feature added in v1.2.0-rc1, on `dev` branch currently.

**Comment by Majiir** [comment]
I've tested `v1.2.0-rc1` and this is working great so far. Thanks!
