### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by dlrudie** [z4yx/pam_rssh#3]
First, thank you for this. pam_ssh_agent_auth does not support ed25519-sk for use with sudo so this project looks promising.

Unfortunately, I am 100% unfamiliar with rust and cargo.

In simply cloing the repository and running cargo build --release I am presented with an error.
```rust
    Updating crates.io index
error: failed to get `pam` as a dependency of package `pam_rssh v0.2.0 (/home/dopefish/builds/pam_rssh)`

Caused by:
  failed to load source for dependency `pam`

Caused by:
  Unable to update /home/dopefish/builds/pam_rssh/dep/pam-rs/pam

Caused by:
  failed to read `/home/dopefish/builds/pam_rssh/dep/pam-rs/pam/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

From here I googled pam-rs and found another github repository. In the dep folder I cloned https://github.com/anowell/pam-rs.git.

Again, I built but received another error.

```rust
    Updating crates.io index
error: failed to get `ssh-agent` as a dependency of package `pam_rssh v0.2.0 (/home/dopefish/builds/pam_rssh)`

Caused by:
  failed to load source for dependency `ssh-agent`

Caused by:
  Unable to update /home/dopefish/builds/pam_rssh/dep/ssh-agent.rs

Caused by:
  failed to read `/home/dopefish/builds/pam_rssh/dep/ssh-agent.rs/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I searched online for ssh-agent.rs and found an other github repository. Just like before I cloned https://github.com/sekey/ssh-agent.rs.git.

I went back to build again and received yet another error.

```rust
    Updating crates.io index
error: no matching package named `pam` found
location searched: /home/dopefish/builds/pam_rssh/dep/pam-rs/pam
required by package `pam_rssh v0.2.0 (/home/dopefish/builds/pam_rssh)`
```

There is a pam folder inside of pam-rs from the repository.

I have been unable to get past building at this point.

Help is appreciated!

**Comment by dlrudie** [comment]
I found that both pam-rs and ssh-agent.rs were both on crates.io so I edited Cargo.toml to pull from crates.io.

```diff
12,13c12,13
< pam = { path = "./dep/pam-rs/pam" }
< ssh-agent = { path = "./dep/ssh-agent.rs" }
---
> pam-bindings = "^0.1.1"
> ssh-agent = "^0.2.4"
```

However, it will get to the same exact spot as the build errors above with the same 10 errors.

**Comment by dlrudie** [comment]
Sorry for all the posts, just documenting my progress. Digging into it a little bit more I see that there are submodules that were not downloaded with cloning the repo. I cloned it with --recurse-s asubdf awe s A

**Comment by z4yx** [comment]
Thanks for sharing your experience. I've updated the README in case someone runs into the same problem.
