### ISSUE TITLE
two minor changes

### ISSUE THREAD

**Issue by aphuang2013** [z4yx/pam_rssh#5]
1) rustc 1.66 want to treat PamHandle differently, adding &mut fix that.

*** orig/lib.rs	2022-12-27 06:29:57.846782481 -0800
--- src/lib.rs	2022-12-27 06:23:00.133932449 -0800
***************
*** 73,79 ****
  }
  
  impl PamHooks for PamRssh {
!     fn sm_authenticate(pamh: &PamHandle, args: Vec<&CStr>, _flags: PamFlag) -> PamResultCode {
          /* if (flags & pam::constants::PAM_SILENT) == 0 */
          {
              setup_logger();
--- 73,79 ----
  }
  
  impl PamHooks for PamRssh {
!     fn sm_authenticate(pamh: &mut PamHandle, args: Vec<&CStr>, _flags: PamFlag) -> PamResultCode {
          /* if (flags & pam::constants::PAM_SILENT) == 0 */
          {
              setup_logger();
***************
*** 171,177 ****
      }
  
      // Always return PAM_SUCCESS for sm_setcred, just like pam-u2f
!     fn sm_setcred(_pamh: &PamHandle, _args: Vec<&CStr>, _flags: PamFlag) -> PamResultCode {
          info!("set-credentials is not implemented");
          PamResultCode::PAM_SUCCESS
      }
--- 171,177 ----
      }
  
      // Always return PAM_SUCCESS for sm_setcred, just like pam-u2f
!     fn sm_setcred(_pamh: &mut PamHandle, _args: Vec<&CStr>, _flags: PamFlag) -> PamResultCode {
          info!("set-credentials is not implemented");
          PamResultCode::PAM_SUCCESS
      }
2) pam-rs changed to package reference to pam-bindings, so updated Cargo.toml to use crate.io entry
pam-bindings = "^0.1.1"

the build was successful and used it in some of my machines now.

**Comment by z4yx** [comment]
Not reproduced with `rustc 1.66.0 (69f9c33d7 2022-12-12)`. Did you update any submodule when you found build errors?

**Comment by aphuang2013** [comment]
=== I could not get thru with rustc, this is on ubuntu
error[E0053]: method `sm_setcred` has an incompatible type for trait
   --> src/lib.rs:174:26
    |
174 |     fn sm_setcred(_pamh: &PamHandle, _args: Vec<&CStr>, _flags: PamFlag) -> PamResultCode {
    |                          ^^^^^^^^^^
    |                          |
    |                          types differ in mutability
    |                          help: change the parameter type to match the trait: `&mut PamHandle`
    |
    = note: expected fn pointer `fn(&mut PamHandle, Vec<&CStr>, _) -> PamResultCode`
               found fn pointer `fn(&PamHandle, Vec<&CStr>, _) -> PamResultCode`
============================
rustc 1.66.0 (69f9c33d7 2022-12-12)

**Comment by z4yx** [comment]
I guess you are using the pam submodule from upstream (https://github.com/anowell/pam-rs) instead of my fork. Recent updates from upstream have changed `_pamh` to mutable.

**Comment by z4yx** [comment]
The problem should be solved after merging #10 .
