### ISSUE TITLE
Ready for distribution / production ?

### ISSUE THREAD

**Issue by smortex** [z4yx/pam_rssh#8]
Hey!

According to the README:

> It's a preliminary version now. Test and feedback are needed.

Just build and installed it on my Debian machine, and it works like a charm :heart_eyes: !

Can we consider this ready for production?  If so, I would suggest creating a tag so that there is an "anchor" in the project for packagers to build packages (rather than using a git tag that does not necessarily tells much).  If you intend to follow [semver](https://semver.org/), that might be a `1.0.0` tag meaning it can be used in production.  I would then be pleased to package this for FreeBSD!

If you think that more work is required before considering this ready for production, it might still make sense to tag the code as a pre-release version.  In this case, can you detail what you would like to be done and how we can help?

Thanks!

**Comment by smortex** [comment]
For the record, this was also tested successfully on FreeBSD after applying the patch in #10.  I am considering submitting a port for it and would really like to have a version number to do so and not have to rely on a fake version in the form of the date as YYYYMMDD :grin: .

**Comment by z4yx** [comment]
Thank you for testing this project on FreeBSD.
Actually, I've deployed this module on some production servers for some time. And it works well. So, I agree to mark it as a pre-release or RC version. I'm going to update the doc and add a tag right now.

**Comment by smortex** [comment]
Awesome!  I just pushed a [FreeBSD port for pam_rssh](https://www.freshports.org/security/pam_rssh/).

FreeBSD packages will be available for FreeBSD users soon!

**Comment by jeremie-H** [comment]
I've integrated this project in my terraform/ansible deployment for new VM, and i confirm that it's working for a year without any issues :heart_eyes: 
thanks for your work !

**Comment by JamieMagee** [comment]
I have a PR open to package this for NixOS: https://github.com/NixOS/nixpkgs/pull/209962
